"""Changes in userlocations table

Revision ID: 067bcdcd51be
Revises: 0d40872413ac
Create Date: 2024-06-19 02:55:58.625303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '067bcdcd51be'
down_revision: Union[str, None] = '0d40872413ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('userlocations_location_id_fkey', 'userlocations', type_='foreignkey')
    op.create_foreign_key(None, 'userlocations', 'locations', ['location_id'], ['location_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('userlocations_location_id_fkey', 'userlocations', type_='foreignkey')
    op.create_foreign_key('userlocations_location_id_fkey', 'userlocations', 'locations', ['location_id'], ['location_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
