"""Added is_owner in users

Revision ID: 75f7a26a39a2
Revises: 067bcdcd51be
Create Date: 2024-06-25 13:12:06.371005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75f7a26a39a2'
down_revision: Union[str, None] = '067bcdcd51be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_owner', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_owner')
    # ### end Alembic commands ###
